- src/plugins/irc/irc-channel.c
- src/plugins/irc/irc-channel.h
- src/plugins/irc/irc-nick.c
- src/plugins/irc/irc-nick.h
- src/plugins/irc/irc-protocol.c
- src/plugins/irc/irc-server.c
- src/plugins/irc/irc-server.h
- src/plugins/irc/irc-upgrade.c
What the title says, might break some scripts because I've changed some variables.
**Edit:** again, I didn't add it to the help yet.
> irc: add support for CAP account-notify

- src/core/weechat.c
If environment variable WEECHAT_HOME is set to a non-empty value, this
is taken as the path for Weechat home directory.
"--dir" command-line switch has higher precedence over this
environment variable.
> Respect environment variable WEECHAT_HOME

- src/plugins/irc/irc-protocol.c
Fixes #376. This avoids warnings for WHOX messages that we do not parse/
understand yet. Previously, IRC_PROTOCOL_MIN_ARGS was 5 where it should
have been 4 (which avoids warnings for WHOX commands only requesting one
WHOX type). Changing the behavior to support all different WHOX types
seems like a bad idea to me, as it's quite hard to figure out which
information was requested with the WHOX command.
> irc: avoid warnings for unsupported WHOX messages

- ChangeLog.asciidoc
- src/plugins/relay/relay-client.c
When relay plugin gets a new successfull handshake for a relay
connection using websocket it will look for HTTP header X-Real-IP which
is commonly used when proxying connections. This allows users of WeeChat
and proxy to see the client's real IP address instead of the address of
the HTTP proxy.
> relay: print value of HTTP Header X-Real-IP

- src/plugins/irc/irc-color.h
- src/plugins/irc/irc-config.c
- src/plugins/irc/irc-config.h
- src/plugins/irc/irc-protocol.c
This patch adds an option to change the color which is used to print the current channel topic into the chat buffer when it is shown on join or as reply to `/topic`, making it possible to configure that color just like on topic changes. By default, behavior is identical to before.
*Feature found to be missing by someone at #weechat a while ago.*
> irc: add separate color option for current topic in channel buffer

- doc/en/weechat_dev.en.asciidoc
- doc/fr/weechat_dev.fr.asciidoc
- doc/ja/weechat_dev.ja.asciidoc
- src/core/wee-command.c
- src/plugins/alias/alias.c
Couple of places in the core and docs still contained old `/alias` syntax being used.
> core: update examples of alias add commands

- src/core/wee-command.c
Applies to `/uptime -o` which doesn't use translations and handles singular/plural itself directly.
> core: fix /uptime output for 0 days

- doc/en/weechat_faq.en.asciidoc
1. Freenode supports DH size 2048 nowadays, so change the network to
example.
2. Freenode has valid SSL certificate, so also change that network to
example.
3. Mention irc.server.example.ssl_fingerprint. I used SHA512 sum of
weechat.org's certificate as it was the first one to come to mind.
> doc: fix "I have SSL problems"

- doc/docgen.py
This PR modifies the `docgen.py` script to add an anchor to every hdata under [hdata_get](https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_hdata_get). It also turns all the hdata names into clickable links to easily access the anchor as the items are not listed in TOC.
This solves #532 in the most basic sense.
*Tested by myself by generating english plugin API reference.*
> doc: add clickable anchors to hdata listing in plugin API reference

- po/de.po
I’m not sure whether I have to update the headers in the po file …
> core: fix typo in German translation

- src/plugins/javascript/weechat-js-api.cpp
The error message is as follows:
```
/usr/ports/irc/weechat/work/weechat-1.3/src/plugins/javascript/weechat-js-api.cpp:4206:16: error: use of undeclared identifier
'localtime'
date_tmp = localtime (&time);
^
/usr/ports/irc/weechat/work/weechat-1.3/src/plugins/javascript/weechat-js-api.cpp:4208:9: error: use of undeclared identifier
'strftime'
strftime (timebuffer, sizeof (timebuffer), "%F %T", date_tmp);
^
```
> Fix build on FreeBSD

- src/core/wee-log.c
This typo has been bugging me for the *longest* time, so I decided to fix it.
> Fixed a typo in wee-log.c

- src/core/wee-config.c
- src/core/wee-config.h
The option was added in c1c1005b364d28409339f46b5233bcb0f2f86ed7 but throughout all git code history has never been actually used. `weechat.color.nicklist_away` is used for away nicks in nicklist instead.
*Brought to my attention by gb in #weechat.*
> core: remove unused option weechat.color.nicklist_offline

- src/plugins/trigger/trigger-buffer.h
- src/plugins/xfer/xfer-config.h
This was causing trouble in osx linking
duplicate symbol _trigger_buffer in:
.libs/trigger.o
.libs/trigger-buffer.o
and others (same error)
> Add extern keyword several places to link in osx

- AUTHORS.asciidoc
- src/plugins/irc/irc-command.c
This makes `/ctcp` syntax like `/msg`'s.
*Also includes my nickname in AUTHORS :)*
> irc: add multiple targets and -server option to /ctcp (closes #204)

- cmake/FindPython.cmake
When linking against a python with shared libraries, this script ONLY asked for the LD flags, not any additional libraries.  This could result in a condition where required libraries (such as libutil on Centos 6.7 against Python 2.7) are not loaded and the load of the plugin thus fails.  This change asks the python being linked against which libraries it was linked using, and then ensures those are also linked against by the python plugin for weechat.
> Python plugin shared libraries missing

- src/plugins/xfer/xfer-dcc.c
When signals (e.g. `SIGWINCH` for terminal resize) are fired they cause poll to fail with `EINTR`, erroring file receival even when there wasn't a problem with it.
This patch adds additional checks for `EINTR` and `EAGAIN` that cause retry of poll, since both are unrelated to actual file receival.
> xfer: ignore signals when polling socket during file receive (closes #677)

- configure.ac
> zlib: Fix package name in error message if zlib was not found.

- src/plugins/irc/irc-config.c
- src/plugins/irc/irc-config.h
- src/plugins/irc/irc-protocol.c
Previously SASL did not fail when it was set up for the server but wasn't supported by it. This makes no difference when the server's sasl_fail is set to "continue" but might make a difference if set to "disconnect" or "reconnect".
To make sure server connection is not made under such circumstances, this patch adds an extra configurable ("on" by default) check to trigger SASL failure when it is set up but not supported by the server. Although not directly a SASL failure, this makes SASL not-authenticated scenarios all handled consistently, while providing extra security by not silently ignoring not being authenticated as requested.
> irc: add option irc.network.sasl_fail_unavailable (closes #600)

- cmake/FindIconv.cmake
Instead of splitting ${ICONV_LIBRARY}'s path and then assuming the
library is called "libiconv.so", use ${ICONV_LIBRARY}'s entire value in
the calls to check_library_exists().
If that is not done, the iconv detection fails if one sets ICONV_LIBRARY
to, for example, /usr/lib/libc.so, as the previous calls would still
pass "-liconv" to the linker instead of the chosen value.
> FindIconv: Stop hardcoding the library name.

- src/core/wee-string.c
- tests/unit/core/test-string.cpp
The separator for string_split_command was hardcoded (`;`) instead of using the one from the function's arguments.
Not only did it not split strings with a different separator, it crashed WeeChat when `;` existed somewhere in the string.
It probably went unnoticed because in WeeChat's codebase it is only used with `;` as a separator.
I have modified the unit test to check whether it works with separator different than `;`.
> core: fix the hardcoded separator in string_split_command

- src/plugins/irc/irc-protocol.c
The following server command makes weechat crash: ``:blah 734 a b c\r\n``. This patch (which is copy/paste of ``IRC_PROTOCOL_CALLBACK(733)``) should fix this issue.
> irc: fix NULL pointer dereference in 734 command callback

- src/core/wee-network.c
- src/plugins/irc/irc-server.c
- src/plugins/xfer/xfer.c
With weechat, if the network changes in anyway that causes resolv.conf
to be updated, that is not picked up, resulting in
irc: connecting to server XXXX.com/1026 (SSL)...
irc: address "XXX.com" not found
irc: error: Name or service not known
irc: reconnecting to server in 30 seconds
This happens, especially when one connects to an irc server behind a
VPN.
This can also happen when there is no network connectivity weechat was started
but later network is connected to.
The fix is simple, it relies on calling  res_init (3) before getaddrinfo in
network_connect_child and other places.
res_init reloads the resolv.conf and getaddrinfo does not fail with
address resolution error.
> Use res_init before getaddrinfo.

- doc/en/weechat_user.en.asciidoc
- src/plugins/trigger/trigger-callback.h
- src/plugins/trigger/trigger-command.c
- src/plugins/trigger/trigger-completion.c
- src/plugins/trigger/trigger-config.c
- src/plugins/trigger/trigger-config.h
- src/plugins/trigger/trigger.c
- src/plugins/trigger/trigger.h
This patch adds a new option `once_action` to triggers, which by default is `none` but also allows `disable` (to disable the trigger after it executes) and `delete` (to delete the trigger after it executes). This action is run after stopping the trigger so it can be deleted.
> trigger: add support for one-time triggers (closes #399)

- doc/en/weechat_plugin_api.en.asciidoc
- src/core/wee-eval.c
When 'extra' option in a call to `eval_expression` is set to `eval`, all the extra_vars defined will be evaluated with the same settings before replacing in the result. This does not change the current default behavior but allows for dynamic content in extra variables.
> core: add extra_vars evaluation option to eval_expression

- src/plugins/irc/irc-server.c
The issue was server->sock not being set unless the connection was successful. In the case of SSL connections, a connection could be established but not be successful because it wasn't an SSL port or the SSL certificate did not validate.  In those cases irc_server_close_connection() was called, but it was checking for server->sock != -1 before calling gnutls_bye() or close().  Since close() was never called for the socket, it would get stuck in the CLOSE_WAIT state until weechat was closed.
This will also fix issue #573 when the unclosed sockets exceed the fd limit.
> Fix for unclosed/leaking sockets from issue #358

- tests/ncurses-fake.c
I get this error compiling 1.7-dev on Fedora 24:
[ 98%] Built target weechat
[100%] Creating symbolic link weechat-curses
[100%] Built target weechat-curses
../src/gui/curses/libweechat_gui_curses.a(gui-curses-window.o): In function `gui_window_save_style':
gui-curses-window.c:(.text+0x44c): undefined reference to `wattr_get'
../src/gui/curses/libweechat_gui_curses.a(gui-curses-window.o): In function `gui_window_restore_style':
gui-curses-window.c:(.text+0x518): undefined reference to `wattr_set'
../src/gui/curses/libweechat_gui_curses.a(gui-curses-window.o): In function `gui_window_emphasize':
gui-curses-window.c:(.text+0xe50): undefined reference to `wattr_get'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/tests.dir/build.make:108: recipe for target 'tests/tests' failed …
> tests: add wattr_get/set to fake

- src/core/wee-string.c
When `HOME` is unset but `WEECHAT_HOME` is set (or provided by `-d` flag) and xfer plugin gets loaded and `xfer.file.upload_path` has the default value of `~` then a SIGSEGV occurs.
Bug found by garbas in #weechat.
```
< garbas> hey, i'm trying to run weechat in tmux via systemd. weechat crashes after i type in the password to uncrypt the secrets. any idea what am i going on? http://sprunge.us/cdLJ   
< garbas> i must be missing something in PATH or some variable is expected but not there                                                                                                 
< garbas> maybe somebody else is aware of some runtime dependency that is causing this crash                                                                                             
< sim642> the …
```
> api: fix string_expand_home SIGSEGV when HOME environment variable unset

- src/core/wee-config.c
- src/core/wee-config.h
- src/gui/curses/gui-curses-chat.c
> core: add option weechat.look.align_multiline_words

- configure.ac
these 3 configure tests were bogus in that they didnt return a result:
```
checking for flock() support...
checking for execinfo.h and backtrace...
checking for eat_newline_glitch support...
```
looking at config.log reveals:
```
configure:24327: checking for eat_newline_glitch support
configure:24344: gcc -c -g -O2 -DHAVE_GNUTLS -D_FILE_OFFSET_BITS=64 ...
conftest.c: In function 'main':
conftest.c:134:2: error: assignment of read-only location '*(cur_term->flags ...
configure:24344: $? = 1
configure: failed program was:
...
configure:24351: result:
```
but due to the misnamed variables configure ended up enabling
eat_newline_glitch.
fixes #814
> core: fix misnamed configure cache variables

- src/plugins/irc/irc-protocol.c
Previously using option values
```
irc.look.buffer_open_before_join off
irc.look.buffer_switch_join on
```
and manually joining a channel which gets forwarded (e.g. `#linux` → `##linux-overflow` on freenode) the channel buffer for `##linux-overflow` was not switched to even though the option says it should
have.
This patch copies manual join and noswitch information for channels which get forwarded.
> irc: fix buffer switching on manual join for forwarded channels

- doc/en/weechat_plugin_api.en.adoc
- doc/fr/weechat_plugin_api.fr.adoc
- doc/it/weechat_plugin_api.it.adoc
- doc/ja/weechat_plugin_api.ja.adoc
The docs provide the following example for deleting localvars on buffers:
/* remove local variable "toto" */
weechat_buffer_set (my_buffer, "localvar_del_toto", NULL);
This does not work, because [`gui_buffer_set`][1] exits immediately if one of the arguments are `NULL`. This PR simply updates the documentation to reflect this, providing the following example instead:
/* remove local variable "toto" */
weechat_buffer_set (my_buffer, "localvar_del_toto", "");
[1]: https://github.com/weechat/weechat/blob/master/src/gui/gui-buffer.c#L1795
> doc: fix examples with localvar_del

- src/plugins/irc/irc-command.c
Previously these commands could only execute commands on all channels/queries/servers except the ones specified. This patch allows the inversion of that behavior, i.e. execute commands only on specified channels/queries/servers via the `-include=` argument.
> irc: add inclusive behavior to /allchan, /allpv, /allserv

- src/plugins/irc/irc-command.c
- src/plugins/irc/irc-mode.h
This pull request provides three things:
1. /ban, /unban, /quiet, /unquiet commands will put as many masks as allowed by `MODES` into a single command, not send them one-by-one (closes #15)
2. /quiet, /unquiet follow format set by `ban_mask_default` for nicknames given as arguments (closes #577)
3. /quiet, /unquiet are only allowed on servers which support them (e.g. UnrealIRCd uses channel mode "q" for owner status, not quiet)
> irc: /ban, /unban, /quiet, /unquiet command improvements

- src/core/wee-config.c
This seems to have been forgotten when config option was removed.
> core: remove config_look_hotlist_add_buffer_if_away completely

- src/core/wee-command.c
- src/core/wee-infolist.h
- src/core/wee-secure.c
- src/gui/gui-bar-item.c
- src/gui/gui-bar-window.h
- src/gui/gui-chat.h
- src/gui/gui-completion.c
- src/gui/gui-completion.h
- src/gui/gui-focus.h
- src/gui/gui-key.c
- src/gui/gui-key.h
- src/gui/gui-layout.h
- src/gui/gui-line.h
- src/plugins/buflist/buflist.h
- src/plugins/exec/exec-config.h
- src/plugins/fifo/fifo.c
- src/plugins/fifo/fifo.h
- src/plugins/irc/irc-buffer.h
- src/plugins/irc/irc-msgbuffer.h
- src/plugins/irc/irc-server.h
- src/plugins/plugin-api.h
- src/plugins/relay/irc/relay-irc.c
- src/plugins/relay/relay-config.c
- src/plugins/relay/weechat/relay-weechat-protocol.h
- src/plugins/relay/weechat/relay-weechat.c
- src/plugins/script/script-config.c
- src/plugins/weechat-plugin.h
I ran CLion's static analysis on weechat source, then manually went through them and fixed some that I found to be the biggest issues. All of these are very small code fixes or just cleaning up code, including:
1. Functions declared with different arguments than defined and called.
2. Local variables created only to use `sizeof` for `malloc`.
3. Missing forward declarations used in some API function arguments.
4. Broken header guard.
5. Unused `#define`-s and global variables.
6. Declared functions that are not defined and used.
7. Callbacks that are not hooked.
8. Unused `struct`s.
9. Callbacks that are no longer used.
It is easier to review these changes commit by commit, not as an entire PR. Feel free to ask any questions or exclude some changes.
> Small fixes and code cleanup for problems found by CLion inspections

- src/plugins/irc/irc-message.c
- src/plugins/irc/irc-sasl.c
Stores that are overwritten anyway before being read. Compilers probably optimize them away, but let's just remove them, nobody is going to be hurt.
Found by the clang static analyzer.
> irc: Remove unnecessary stores

- src/core/wee-config-file.h
so this header can be included even if it's not already included
> Include stdio.h for FILE

- doc/en/weechat_plugin_api.en.adoc
The `weechat-plugin.h` header defines all C API functions through macros on a global `weechat_plugin` struct pointer but this fact is not documented in the plugin API, even though the example and all existing plugins do so.
*Reported by muffindrake in #weechat:*
```
17:38:25 < muffindrake> It's a bit jarring that this isn't mentioned in the plugin api
17:38:52 < muffindrake> You must define a macro weechat_plugin, apparently
17:38:58 < muffindrake> as seen in fset/fset.h
17:39:09 < muffindrake> It compiles fine now.
[...]
17:40:26 < sim642> muffindrake, https://weechat.org/files/doc/stable/weechat_plugin_api.en.html#macros
17:41:20 < muffindrake> sim642: That documentation does NOT mention you need to have a symbol weechat_plugin declared
17:42:28 < sim642> The example shows it still …
```
> doc: mention weechat_plugin pointer used by plugin header

- po/cs.po
> Fixed typo in "pzthon"

- src/gui/curses/headless/main.c
From the getdtablesize(3) man page:
It is not specified in POSIX.1; portable applications should
employ sysconf(_SC_OPEN_MAX) instead of this call.
Specifically, this fixes a compilation problem on Android.
> Replace getdtablesize() with sysconf(_SC_OPEN_MAX)

- doc/de/weechat_user.de.adoc
- doc/en/weechat_user.en.adoc
- doc/fr/weechat_user.fr.adoc
- doc/it/weechat_user.it.adoc
- doc/ja/weechat_user.ja.adoc
- doc/pl/weechat_user.pl.adoc
Generated with:
```console
$ sed -i 's|openssl ecparam -genkey -name prime256v1 >~/.weechat/ecdsa.pem|openssl ecparam -genkey -name prime256v1 -out ~/.weechat/ecdsa.pem|' $(git grep -l 'openssl ecparam')
```
There's no reason to involve shell redirection, which we've had since 88073243.  We already use `-in` or `-out` for our other `openssl` invocations, as shown by:
```console
$ git grep 'openssl.*\(<\|>\|-in\|-out\)' doc/en
doc/en/weechat_user.en.adoc:$ openssl req -nodes -newkey rsa:2048 -keyout nick.pem -x509 -days 365 -out nick.pem
doc/en/weechat_user.en.adoc:$ openssl ecparam -genkey -name prime256v1 -out ~/.weechat/ecdsa.pem
doc/en/weechat_user.en.adoc:$ openssl ec -noout -text -conv_form compressed -in ~/.weechat/ecdsa.pem | grep '^pub:' -A 3 | tail -n 3 | tr -d ' \n:' | xxd -r -p …
```
> doc: use '-out' instead of shell redirection for openssl ecparam

- src/plugins/xfer/xfer-config.c
- src/plugins/xfer/xfer-config.h
- src/plugins/xfer/xfer-dcc.c
- src/plugins/xfer/xfer.c
- src/plugins/xfer/xfer.h
PR pendant of #1167.
I'll be shutting down my network now but I've hogged up quite a bit with just `TCP_NODELAY`, it works as a workaround and doesn't seem to have any obvious drawback, so we can probably use that for everyone safely.
I still don't like that the xfer logic sometimes disable intermediate acks at runtime based on retry-able error though so I'd also like to add the option even if I haven't needed it, I can remove that second commit if you think it's fluff. Given there is no message when that auto-disabling happens (and I don't see how to display something easily from the fork child) I can't really say how often it has but it feels too frequent...
> workaround/fix DCC get hangs

- doc/en/weechat_plugin_api.en.adoc
- src/core/wee-hashtable.c
- src/core/wee-hashtable.h
- src/plugins/irc/irc-channel.c
- src/plugins/irc/irc-command.c
- src/plugins/irc/irc-nick.c
- src/plugins/irc/irc-protocol.c
- src/plugins/irc/irc-server.c
- src/plugins/irc/irc-server.h
- src/plugins/irc/irc-upgrade.c
- src/plugins/plugin.c
- src/plugins/weechat-plugin.h
- tests/unit/core/test-hashtable.cpp
In addition to implementing required changes to support capabilities with values and `CAP LS`/`CAP LIST` split across multiple lines, this patch also adds client-side tracking of all capabilities. This means that weechat/plugins/scripts/triggers can easily check if some capability is available or enabled, instead of having to somehow check itself.
This also modifies `/cap` command to uppercase the subcommand which it can autocomplete because servers may require it to be uppercase.
API was changed to allow keeping track of server capabilities across upgrading so the hashtable needs to be restored from an infolist.
There's a few places with comments like `WeeChat x.y.z` which need to be updated to the proper WeeChat version this gets merged into.
_NB! This patch is in conflict with #580. I …
> irc: add support for IRCv3.2 Client Capability Negotiation (closes #586)

- src/core/wee-network.c
When there are multiple addresses for a server and a TLS handshake failure
occurs, the next server in the list will connect and then timeout without
performing any TLS handshake.
This is because irc_server_close_connection closes server->sock so the next
pipe to be created reuses that fd, but the hook for the handshake fd still
exists when the next connection attempt is started.
The hook for network_connect_child_read_cb is never added because a hook
for the reused fd number still exists.
Resolve this by removing the handshake hook before calling the connect
callback.
```
│12:05:42    z_je  -- irc: connecting to server irc.z.je/6697 (SSL)...
│12:05:42    z_je  -- irc: retry=0 ssl=1 gnutls=0x55fe1c9689b0...
│12:05:42 weechat     debug: adding hook: type=5 (connect), plugin="irc", …
```
> core: unhook TLS handshake fd before calling connect callback

- configure.ac
Update configure.ac to explicitly link the v8 plugin with -lpthread to fix detection and compilation on some Linux distributions.
> Fix v8 plugin for some Linux distributions

- autogen.sh
autoreconf -f overwrites user installed GNU auto* files like config.sub and config.guess
> don't overwrite user installed GNU auto* files

- src/core/wee-command.c
The ability to check localvars for a buffer different than the current one is something I've felt the need for multiple times when debugging scripts or triggers. It's annoying to switch to the needed buffer just to issue that one command to see the output in core buffer again.
It might be nice to also allow localvar `set` and `get` subcommands to specify buffer name but that'd probably require an optional `-buffer` flag, not just extra argument to keep compatibility.
Happy Hacktoberfest!
> core: allow specifying buffer number/name for /buffer localvar

- src/plugins/lua/weechat-lua-api.c
All other scripting languages return ERROR, lua being the only exception.
> lua: mkdir API functions should return ERROR on error.

- po/cs.po
original: <op> byl vykopnut <user> results in confusing message caused by mistranslation: op was kicked user
proposed fix: <op> vykopnul <user> should result in more understandeable message: op has kicked user
> Fix czech translation kick message

- src/plugins/aspell/weechat-aspell.c
Aspell plugin's `weechat_aspell_string_is_nick` uses `nick_completer` to avoid showing spelling errors for nicknames in tab completed situations. Since 2.4 the `nick_completer` by default ends with a trailing space, which aspell doesn't account for.
This PR makes aspell strip all trailing spaces from `nick_completer` before considering it and fixes issue #1306. Repeatedly stripping the option string on every input modification might not be the best, so maybe some optimization should be added instead.
> aspell: strip trailing spaces from nick_completer (closes #1306)

- src/core/wee-command.c
- src/core/wee-config.c
- src/gui/gui-filter.c
- src/gui/gui-filter.h
Implemented my suggested solution from #1309: `gui_filter_all_buffers` now has an optional `t_gui_filter*` argument to only refilter buffers which the specified filter affects.
My testing confirms that adding/enabling/toggling/disabling/removing filters which affect one buffer is significantly faster, enough to turn `grep_filter.py` from unbearably slow to essentially instant.
> gui: only refilter affected buffers on filter change

- src/plugins/irc/irc-command.c
- src/plugins/irc/irc-protocol.c
- src/plugins/irc/irc-server.c
`/nick :)` results in the user's nick being changed to `)` rather than a server error. Use : before %s in each `NICK` command to avoid this.
> irc: quote argument to NICK

- doc/en/weechat_quickstart.en.adoc
Put everything help-related first, then explain how to set options.
> quick start guide: rearrange content in section 2

- cmake/FindNcurses.cmake
- src/gui/curses/gui-curses-color.c
- src/gui/curses/gui-curses-window.c
- src/gui/curses/gui-curses.h
- src/gui/curses/headless/ncurses-fake.c
- src/gui/curses/headless/ncurses-fake.h
This PR fixes issue #1343:
1. All uses of the problematic `COLOR_PAIR` macro replaced with functions that allow up to 32767 color pairs (`short` datatype size limit in both the ncurses functions and WeeChat's color pair table).
2. Transposed the color table in `/color` buffer (and command line option `-c`) to sensibly allow showing more than 255 pairs.
For testing I used my [`colorspam.py`](https://gist.github.com/sim642/dde23725f23907bc960fce308ecda4f1) script.
Needs to be verified that the `setcchar` function with its `wchar_t*` argument is usable in all curses setups. Could be that this needs to be put behind a preprocessor flag to work on curses libraries without wide char support or something like that.
> gui: support up to 32767 ncurses color pairs (issue #1343)

- src/plugins/irc/irc-protocol.c
The motivation for this patch came from aliases which allow specifying commands with and without the command character. Server `.command` variables could easily do the same without negative consequences because previously without the command character it would simply attempt to send text into the server buffer, only to end up with an error message.
> irc: make command characters optional in server's command option

- doc/en/weechat_user.en.adoc
While the documentation for Logger filename masks contained examples, it didn't actually describe it would try to match in order of descending specificity.
> Added introductory description of Logger masks

- src/plugins/irc/irc-command.c
- src/plugins/irc/irc-config.c
- src/plugins/irc/irc-server.c
- src/plugins/irc/irc-server.h
Closes issue #115.
In my (limited) testing, it seems fine to pass `""` as password when the certificate's private key is not encrypted.
Happy Hacktoberfest!
> irc: add server option ssl_password for SSL certificate private key password (issue #115)

- src/plugins/irc/irc-config.c
- src/plugins/irc/irc-server.c
Due to this ssl_password will be partially unused with GnuTLS < 3.1.0.
In that case an encrypted SSL client cert import will simply fail.
Even though GnuTLS 3.0.21 seems to have `gnutls_x509_privkey_import2` according to its git log, it is again missing from 3.0.22, which is weird. Based on their NEWS file, it was added in 3.1.0 so I decided to be safe and rely on that.
> irc: fix compilation with GnuTLS < 3.1.0 (issue #115)

- doc/de/autogen/plugin_api/infos.adoc
- doc/en/autogen/plugin_api/infos.adoc
- doc/fr/autogen/plugin_api/infos.adoc
- doc/it/autogen/plugin_api/infos.adoc
- doc/ja/autogen/plugin_api/infos.adoc
- doc/pl/autogen/plugin_api/infos.adoc
- src/plugins/plugin-api-info.c
Add info "weechat_headless" so scripts can determine if weechat is running headless. Useful for remote interfaces that utilize push notifications only when weechat is inactive.
> api: add info "weechat_headless"

- cmake/FindGuile.cmake
- configure.ac
- src/plugins/guile/weechat-guile-api.c
- src/plugins/guile/weechat-guile.c
This adds support to cmake for `guile-3.0.0` and adds missing includes which are presumably included with older guile versions.
> Fix the build with guile-3.0.0.

- cmake/FindRuby.cmake
During Ruby 2.7 transition in Ubuntu I tried this patch and weechat builds fine against it.
> core: add detection for Ruby 2.7

- src/plugins/irc/irc-protocol.c
This PR fixes a bug reported on IRC:
```
17:28:11 < oxek> I want to verify a possible bug in weechat. If I do `/who grumble` the last part of (RAINBOW GECOS), i.e. the 'S' and ')' are both colored. Afaik the ')' should not be colored.
17:28:40 < oxek> can someone please verify?
17:29:03 < grumble> oxek: yup the closing paren is bold and pink :)
17:29:20 < grumble> i wouldve put a color reset char in the ident but actually that doesnt fit
17:29:35 < grumble> er i mean in the gecos not ident
17:29:47 < oxek> but shouldn't weechat handle that?
17:30:14 < oxek> i.e. the () are added by weechat, right?
17:31:22 < oxek> grumble: btw sorry if I spammed you with /whois /who etc. I know you're freenode staff, please don't ban me.
17:31:44 < grumble> yes, ideally weechat would reset its colors i …
```
> irc: fix realname delimiter color in WHO/WHOX response

- src/gui/gui-bar-item.c
Supporting multiple lines in the input bar is useful even for buffers
without input_multiline set, because it enables you to compose multiple
lines at once, even if it is sent as multiple messages. It is
particularly useful when you paste multiple lines and want to edit some
of it before you send the message.
> core: properly display newlines in input for all buffers

- src/core/wee-command.c
This allows you to use the `/buffer notify` command without any arguments to display the notify level for the current buffer instead of setting it.
> core: Allow displaying notify level with /buffer notify

- src/plugins/guile/weechat-guile-api.c
- src/plugins/guile/weechat-guile.c
The commit messages should speak for themselves. This functionality broke when support for Guile 2.2 was added in #1098.
The documentation for Guile I/O Extensions is [here](https://www.gnu.org/software/guile/docs/docs-2.2/guile-ref/I_002fO-Extensions.html).
> guile: fix output to buffers and re-enable /guile eval

- src/plugins/irc/irc-command.c
currently /help voice does not tell you that you need -yes if you are using *. i have changed it to match /help op, /help deop and /help devoice
> add -yes to output of /help voice

- ChangeLog.adoc
- src/plugins/irc/irc-channel.c
- src/plugins/irc/irc-command.c
- src/plugins/irc/irc-config.c
- src/plugins/irc/irc-server.c
- src/plugins/irc/irc-server.h
`!` was removed from the default chantypes in 4a42cda3a5f5b02d8ba9afae129499c26250d334 which broke `!channels` on at least one old server where the ircd doesn't send a `005` to specify the chantypes at all. If channels aren't recognized as channels, any incoming messages on them are shown as private messages which makes the channel a bit hard to use.
This PR adds a configuration option for chantypes which is only used if the server doesn't specify them, so that such servers can manually be fixed on the client side.
If supporting outdated servers is out of scope, feel free to close.
> irc: make default chantypes configurable

- src/gui/gui-buffer.c
If you run /input jump_next_visited_buffer right after switching to a
buffer, weechat changes to the first buffer in the visited buffers list.
That is, it wraps around and goes to the buffer you visited the longest
ago. This patch fixes that.
The reason it happens is that when you switch to a buffer (normally,
i.e. in another way than using jump_previously_visited_buffer/
jump_next_visited_buffer) gui_buffers_visited_index is set to -1 (in
gui_buffer_visited_add). This makes gui_buffer_visited_get_index_next
return 0 because it returns gui_buffers_visited_index + 1, which makes
gui_input_jump_next_visited_buffer jump to the first buffer in the list
of visited buffers.
Fixes #1591
> core: Prevent switching to start of visited buffers when jumping to next

- src/plugins/buflist/buflist.c
This used pointer1 and pointer2 which are pointers to the buffers, but
it should use ptr_hotlist1 and ptr_hotlist1 which are pointers to the
hotlists it is trying to compare.
> buflist: Fix wrong pointers being used in hdata_compare

- doc/en/weechat_user.en.adoc
In cf93e953b the `weechat.bar.*.condition` examples have been changed to use `${info:term_width}` instead of `${window.win_width}`. The user guide still shows the old example. This commit syncs the user guide with the on-line help.
I stumbled over this while trying to configure a condition for the buflist. I don't know how doc updates are handled with weechat. I could replace the example in all doc/*/weechat_user.*.adoc` files, but I can't change the description of the example in all languages (all I can offer is german).
> doc: Update weechat.bar.*.condition to use info:term_width

- CMakeLists.txt
- config.h.cmake
- src/core/wee-debug.c
mallinfo() is deprecated in glibc 2.33
https://sourceware.org/pipermail/libc-alpha/2021-February/122207.html
> core: Use mallinfo2() when available

- src/core/weechat.h
wee-eval.c calls gettext directly, but gettext is not a function if
ENABLE_NLS is off. Fix by defining a gettext macro (that expands to its
first argument) if NLS support is disabled.
> core: fix build error if ENABLE_NLS is OFF

- src/gui/gui-bar.c
From my understanding `weechat.bar.$bar_name.size_max` and `weechat.bar.$bar_name.size` are actually defined in lines, not characters, yet the help text mentioned *chars*.
Thanks to christophergray for pointing this out on IRC.
> bar.size and bar.size_max should refer to lines

- src/core/wee-config.c
- src/core/wee-config.h
As far as I can see, this option is not used anywhere and should have
been removed in commit 6e69f7f3c.
> Remove old and unused config option weechat.plugin.debug

- doc/en/weechat_plugin_api.en.adoc
- doc/en/weechat_scripting.en.adoc
- src/plugins/guile/weechat-guile-api.c
- src/plugins/javascript/weechat-js-api.cpp
- src/plugins/perl/weechat-perl-api.c
- src/plugins/php/weechat-php-api.c
- src/plugins/python/weechat-python-api.c
- src/plugins/python/weechat.pyi
- src/plugins/ruby/weechat-ruby-api.c
- src/plugins/tcl/weechat-tcl-api.c
The plugin API function config_new_option accepts null as the
default_value and/or value however the scripting APIs (except for lua)
didn't allow sending null as a parameter value, so it was impossible to
use it this way. This allows sending a null value for these parameters.
Lua already supported sending in nil for these parameters and it works
as expected, so nothing is changed for this plugin.
For Guile you can now send in #nil, for JavaScript null or undefined,
for Perl undef, for PHP NULL, for Python None, for Ruby nil and for Tcl
$::weechat::WEECHAT_NULL.
In all of these languages except Tcl this is the special value
indicating a missing value. However Tcl only has one type, string, so it
doesn't have a null value. Therefore I created a constant with the value …
> scripts: allow null values in config_new_option

- src/plugins/php/weechat-php.c
This reflects an internal API change for PHP 8.2+.
> php: Adjust internal API for PHP 8.2+

- po/sr.po
I have spotted several issues. Removed some more extra spaces, but one is quite bad, so I had to ask for another pull request.
For the future submissions, I will also wrap the .po file to 79 columns...
> core: Serbian message translation fixes

- doc/en/weechat_plugin_api.en.adoc
- doc/fr/weechat_plugin_api.fr.adoc
- doc/it/weechat_plugin_api.it.adoc
- doc/ja/weechat_plugin_api.ja.adoc
- doc/sr/weechat_plugin_api.sr.adoc
When logging this value I just see a number so I have to look up what it means. Previously you would have to check the code or print the value of each of these constants to see it. Seeing the value directly in the documentation makes this much easier.
> doc/api: Add values for hook_process constants

- doc/fr/weechat_plugin_api.fr.adoc
- doc/it/weechat_plugin_api.it.adoc
- doc/ja/weechat_plugin_api.ja.adoc
- doc/sr/weechat_plugin_api.sr.adoc
Only English was changed in commit 197a7a01e.
> doc/api: Fix config_new_option types for non English docs

- tests/unit/core/test-core-util.cpp
util_version_number returns an int, but BYTES_EQUAL only compares the last byte of the int, so it wouldn't test the rest of the int.
I see other tests for functions returning an int use LONGS_EQUAL, so that seems correct to use.
> tests: Use LONGS_EQUAL for version number tests

- src/gui/curses/gui-curses-window.c
> Allow terminal title to be left unchanged.

- doc/en/weechat_plugin_api.en.adoc
- doc/fr/weechat_plugin_api.fr.adoc
- doc/it/weechat_plugin_api.it.adoc
- doc/ja/weechat_plugin_api.ja.adoc
- doc/sr/weechat_plugin_api.sr.adoc
- src/plugins/python/weechat.pyi
I erroneously typed the return types for these to int in commit e0c117e14, but they should be None.
> python: Fix return types for config option callbacks

- src/core/wee-config-file.c
If a color option value is null and is tried being set to an invalid color, the value was set to uninitialized memory which can lead to a segfault.
Can be reproduced with this script:
https://gist.github.com/trygveaa/6ddb3a52f525a7fd8e0908bafa83e07c
The option doesn't have to be set from a script, it also happens with the /set command.
> core: Prevent use of uninitialized memory when setting invalid color

- doc/de/weechat_user.de.adoc
- doc/en/weechat_user.en.adoc
- doc/fr/weechat_user.fr.adoc
- doc/it/weechat_user.it.adoc
- doc/ja/weechat_user.ja.adoc
- doc/pl/weechat_user.pl.adoc
- doc/sr/weechat_user.sr.adoc
The section describes highlight_disable_regex, but the example used highlight_regex instead.
> doc: Fix typo in highlight_disable_regex option name

- doc/de/weechat_scripting.de.adoc
- doc/en/weechat_plugin_api.en.adoc
- doc/en/weechat_scripting.en.adoc
- doc/fr/weechat_plugin_api.fr.adoc
- doc/fr/weechat_scripting.fr.adoc
- doc/it/weechat_plugin_api.it.adoc
- doc/it/weechat_scripting.it.adoc
- doc/ja/weechat_plugin_api.ja.adoc
- doc/ja/weechat_scripting.ja.adoc
- doc/pl/weechat_scripting.pl.adoc
- doc/sr/weechat_plugin_api.sr.adoc
- doc/sr/weechat_scripting.sr.adoc
- src/plugins/guile/weechat-guile-api.c
- src/plugins/guile/weechat-guile.c
- src/plugins/javascript/weechat-js-api.cpp
- src/plugins/javascript/weechat-js.cpp
- src/plugins/lua/weechat-lua-api.c
- src/plugins/lua/weechat-lua.c
- src/plugins/perl/weechat-perl-api.c
- src/plugins/perl/weechat-perl.c
- src/plugins/php/weechat-php-api.c
- src/plugins/php/weechat-php.c
- src/plugins/python/weechat-python-api.c
- src/plugins/python/weechat-python.c
- src/plugins/python/weechat.pyi
- src/plugins/ruby/weechat-ruby-api.c
- src/plugins/ruby/weechat-ruby.c
- src/plugins/tcl/weechat-tcl-api.c
The callback_read and callback_create_option functions in the scripting
APIs always get the value as a string, never as null. This means that if
the value is null, there is no way for the script to distinguish this
from an empty string for string options. This makes it impossible to
properly make options with fallback values, like the irc server and
server_default options, as far as I can see.
All the scripting languages except Tcl use that language's equivalent
for null. For JavaScript which has both null and undefined, null is
used. For Tcl, the magic null string defined in commit 197a7a01e is used
and the documentation is updated to describe that.
I tested this with these scripts:
https://gist.github.com/trygveaa/2d49c609addf9773d2ed16e15d1e3447
You can load all of those scripts and …
> scripts: Send null values to config section callbacks

- doc/en/weechat_plugin_api.en.adoc
- doc/fr/weechat_plugin_api.fr.adoc
- doc/it/weechat_plugin_api.it.adoc
- doc/ja/weechat_plugin_api.ja.adoc
- doc/sr/weechat_plugin_api.sr.adoc
- src/plugins/python/weechat.pyi
These return values were wrong in the description and C example. As can
be seen on lines 2835 and 2873-2903 of src/core/wee-config-file.c the
callback_read function should return the same as the function
config_file_option_set plus the value
WEECHAT_CONFIG_OPTION_SET_OPTION_NOT_FOUND (which is also the same as
the possible return values of config_file_option_set_with_string).
The Python example was already correct and the C example was already
correct in the other languages apart from English.
These errors were introduced in commit 02e2b21d3 and commit 5210ff1ae.
Additionally, the return values in the Python examples didn't include
all the return values. This updates the Python examples to include all
the possible return values for the callbacks in config_new_section, like
it is done in …
> doc/api: Fix return values for callback_read and python examples for config_new_section

- ChangeLog.adoc
- cmake/FindRuby.cmake
- configure.ac
Ruby 3.2 has been released, it is currently not possible to build weechat with it and this PR aims to change that.
based on https://github.com/weechat/weechat/commit/d0c857934b1ce857823b63031439eb00663cada8
> ruby: add detection of Ruby 3.2

- src/gui/gui-input.c
When the input buffer contains non word characters at the end, `/input move_next_word` will stop moving at the end of the last word. This is a bit confusing and not in line with what readline does (think bash).
When there are no words left in the input buffer, make `/input move_next_word` go to the end of line.
> core: allow `/input move_next_word` going to the end of line

- doc/de/weechat_user.de.adoc
- doc/en/weechat_user.en.adoc
- doc/fr/weechat_user.fr.adoc
- doc/it/weechat_user.it.adoc
- doc/ja/weechat_user.ja.adoc
- doc/pl/weechat_user.pl.adoc
- doc/sr/weechat_user.sr.adoc
- src/gui/curses/gui-curses-key.c
- src/gui/gui-chat.c
- src/gui/gui-focus.c
- src/gui/gui-focus.h
- src/gui/gui-window.c
- src/gui/gui-window.h
This contains the single line that you focused on, like _chat_word
contains the word that you focused on. This will be equal to
_chat_line_message if the chat line only contains a single line, but if
the chat line has multiple lines, _chat_line_message will contain all of
them, but _chat_focused_line will only contain the single line that was
focused.
Also adds cursor key l to quote the focused line.
Fixes #1913
> Add _chat_focused_line variable to get the focused line

- src/gui/curses/gui-curses-chat.c
If you have a chat line with multiple lines that were scrolled so that part of it is rendered at the bottom of the chat area, and part of it falls below the chat area, there was a bug where the prefix_suffix would be displayed at the end of the last line.
Looks like this happens because the gui_chat_display_prefix_suffix is called for the line below the last line displayed in the chat area. So we have to add a check for this so we don't add the prefix_suffix. This check is copied from gui_chat_display_word which checks for the same.
Fixes #1912
> core: fix display bug when drawing partially scrolled multiline

- src/gui/curses/gui-curses-chat.c
- src/gui/gui-chat.c
- src/gui/gui-chat.h
- tests/unit/gui/test-gui-chat.cpp
The new rendering of multiline lines had some issues with colors at certain positions not being applied. The color would not be applied if the color code was at either of these positions:
- At the start of a line after a newline character
- At the end of a line after a space and before a newline character
- At a line by itself before a newline character
The way I had done it by considering newline characters as a word in gui_chat_get_word_info with a variable specifying that it's newline characters became messy and didn't really make sense, so rather than doing this, I changed gui_chat_get_word_info to stop before the first newline character. That way, we can just check if we are at a newline character at the start of the loop, and don't need any more special handling.
Fixes #1928
> core: fix chat colors at certain positions not being applied

- src/gui/curses/gui-curses-chat.c
This option was broken with commit 031bd45e3.
> core: fix weechat.look.align_multiline_words not working

- src/core/wee-string.c
- tests/unit/core/test-core-string.cpp
This fixes a bug where if you had multiple lines in the input and pressed ctrl-w when the cursor was after the first word of any line but the first, it would delete both the word before the cursor and the last word on the preceding line.
> core: check for newline character in string_is_whitespace_char

- src/gui/curses/gui-curses-key.c
- src/gui/gui-key.c
- src/gui/gui-key.h
This fixes a couple of issues with these signals and fixes a regression with the vimode.py script that was introduced in WeeChat 4.0.0. See the commit messages for details.
> Fix signals key_pressed and key_combo_*

- src/plugins/fset/fset-bar-item.c
**Description**
**[why]**
The fset.color.help_description setting previously didn't apply to its corresponding UI element, in this case the description of configuration variable in the help bar in fset.
**[how]**
Change code that configures the foreground colour of this UI element to apply the aforementioned setting.
> fset: fix fset.color.help_description not applying

- doc/en/weechat_plugin_api.en.adoc
- doc/fr/weechat_plugin_api.fr.adoc
- doc/it/weechat_plugin_api.it.adoc
- doc/ja/weechat_plugin_api.ja.adoc
- doc/python_stub.py
- doc/sr/weechat_plugin_api.sr.adoc
- src/plugins/python/weechat.pyi
The | syntax for unions is only supported in Python 3.10 and later. Since Python 3.8 and 3.9 are still supported upstream for a while and we had a user reporting on IRC that they couldn't use the stub file since they are using 3.8, change to the old syntax for unions to support this.
There aren't really any drawbacks of this. It's just a bit more verbose, and a typing import is necessary, but neither of those really matters in a generated stub file.
> Add compatibility with Python < 3.10 in weechat.pyi

- src/core/wee-network.c
man pages as well as rpminspect suggest that we shouldn't be using inet_addr().
> core: replace inet_addr() with inet_pton()

- src/gui/curses/gui-curses-color.c
Not sure how big `gui_color_term_colors` can realistically get, but it has type `int` so it's possible to overflow via the multiplication _before_ it is implicitly cast to a `size_t` function parameter.
By explicitly casting to a larger type (`size_t`) _before_ the multiplication, the compiler will implicitly promote the other operands to type `size_t`, avoiding the risk of overflow.
Source: [Chapter 4. Type Conversions, _C in a Nutshell_](https://www.oreilly.com/library/view/c-in-a/0596006977/ch04.html)
> GUI: fix potential integer overflows by casting to `size_t`

- src/gui/gui-window.c
When you run /input search_stop it should scroll to the scroll position the buffer was at before starting the search, rather than to the bottom of the buffer.
Fixes a regression introduced in commit b83b428c5cc48043cb625844b87e94acbc194ba1
Fixes #2093
> core: make search_stop scroll to search start position

- tests/unit/plugins/relay/api/remote/test-relay-remote-network.cpp
Fixes build error on Fedora 40.
> tests: relay: add missing <string.h> include

- src/plugins/tcl/weechat-tcl-api.c
Using API_RETURN_LONG() here breaks tests on i368.
> tcl: fix return value for hdata_longlong

- src/plugins/python/weechat-python.c
Python 3.12 has a bug where it crashes when you unload all the interpreters unless you make sure to unload the first interpreter you loaded last. For some reason, loading the eval interpreter before any scripts also seems to prevent the issue, even if the eval interpreter is unloaded before the other interpreters.
So this just evals an empty string at the end of initing the Python plugin if the Python version is 3.12, to make sure the eval interpreter is loaded first.
Fixes #2046
> python: add workaround for crash on unload with Python 3.12

- src/plugins/lua/weechat-lua.c
/usr/include/lua-5.1/lua.h:19:25: error: token ""Lua 5.1"" is not valid in preprocessor expressions
> lua: fix broken LUA_VERSION check

- cmake/FindLua.cmake
On Fedora, `lua` is an up to date package.
> cmake: find 'lua' first

- src/core/core-crypto.c
This is needed to get `htobe64` defined on Android - see https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/include/sys/endian.h.
> core: Fix build on Android to define htobe64

- CMakeLists.txt
Seemingly unused for ~12 years, since commit a99d13601 ("core: add new plugin "script" (scripts manager, replacing scripts weeget.py and script.pl)")
> cmake: remove unused HAVE_GCRYPT

- src/core/core-debug.c
The gcrypt, gnutls, libcurl and zlib are core libraries/components that we always build against. Remove the #ifdef checks - the symbols must be available at build.
> core: remove ifdef checks for core components

- src/plugins/perl/weechat-perl.c
Apparently the issue with the locale being reset with Perl 5.38 can cause a crash when unloading the scripts on some systems (at least Ubuntu 24.04). There was a workaround added in commit f4b9cad72, but it doesn't work to avoid the crash. However if we set LC_ALL instead of LC_CTYPE the crash doesn't occur.
Fixes #2187
> Fix crash when unloading Perl scripts with Perl 5.38

- src/plugins/python/weechat-python.c
This follows the recommendation from Pythons documentation for PyModule_GetDict where it says:
It is recommended extensions use other PyModule_* and PyObject_*
functions rather than directly manipulate a module’s __dict__.
> python: define constants using PyModule_Add...Constant

- src/gui/curses/headless/ncurses-fake.h
Fixes the following error when building in Fedora rawhide:
error: ‘bool’ cannot be defined via ‘typedef’.
Likely GCC 15 related.
> core: use <stdbool.h> instead of typedef in ncurses-fake.h
