- po/pt_BR.po
This is an update to the pt_BR language file
> Fix some strings for pt_BR.po using msgcheck

- src/plugins/trigger/trigger-config.c
That command is used by the Blinkenshell IRC network. Similar to "ghost".
> Add "recover" to the list of hidden commands.

- README.adoc
Documentation is commonly used in singular form even if it refers to multiple documents.
> Grammar correction

- cmake/FindPHP.cmake
- src/plugins/php/weechat-php.c
Also emit a helpful notice if it cannot find PHP
> php: use find_library to find libphp7.so

- src/plugins/irc/irc-command.c
- src/plugins/irc/irc-command.h
- src/plugins/irc/irc-protocol.c
irc: add nick tag to numeric 341 for consistency
> irc: add support for IRCv3.2 invite-notify

- README.adoc
Restructured sentence to avoid using self-non-descriptive 'this page' anchors.
> Make WeeChat screenshots link more descriptive.

- cmake/FindRuby.cmake
> core: add detection for Ruby 2.6

- src/gui/gui-bar-window.c
Following 9a024f3abadd4b5aacb4793d5edca7827661d468.
> core: fix memory leak in case of error

- doc/de/weechat_faq.de.adoc
- doc/de/weechat_quickstart.de.adoc
typos in doc/de/weechat_faq.de.adoc
typos, spelling, grammar in doc/de/weechat_quickstart.de.adoc
> doc: update German documentation

- CMakeLists.txt
- weechat.desktop
This fixes #408.
Two questions:
* Where should I put the file in the git repository?
* How should I install it from which makefile?
> Add a desktop file

- ChangeLog.adoc
- src/core/wee-command.c
- src/core/wee-command.h
- src/core/weechat.c
- src/core/weechat.h
- src/gui/curses/gui-curses-main.c
Fixes https://github.com/weechat/weechat/issues/1476
> core: reload config on SIGHUP

- src/plugins/fifo/fifo.c
That will make it survive, avoiding the need to reopen it.
> fifo: Open the fifo for writing too

- src/gui/curses/gui-curses-bar-window.c
- src/gui/curses/gui-curses-key.c
This fixes the two issues mentioned in https://github.com/weechat/weechat/issues/1498#issuecomment-626215944.
I don't know if there was any reason for how it was, and if this breaks anything?
> Support consecutive newlines in input bar

- src/plugins/python/weechat-python.c
Related: #1461
Some scripts (eg weechat-matrix) ship directories that need to be imported from the script.
Rather than globally installing the python packages to python's `site-packages` the directories can be installed alongside the script in `WEECHAT_SHAREDIR/python`.
This change adds that directory to the `$PYTHONPATH` to import successfully.
> Add `$weechat_sharedir/python` for global python package import

- doc/en/weechat_user.en.adoc
- src/plugins/trigger/trigger-callback.c
Closes #1567.
Happy Hacktoberfest!
> trigger: add tg_trigger_name variable to all triggers (closes #1567)

- COPYING
- autogen.sh
- doc/de/weechat_faq.de.adoc
- doc/en/weechat_user.en.adoc
- doc/pl/weechat.1.pl.adoc
- doc/pl/weechat_scripting.pl.adoc
- version.sh
Mainly making sure the license file is identical to what is distributed by GNU, since it says to distribute verbatim.
> Minor cleanup

- doc/sr/weechat_user.sr.adoc
Here is an update for the Serbian translation of documentation.
> doc: Update Serbian translation

- doc/python_stub.py
- src/plugins/python/weechat.pyi
This makes it possible to see how functions are used without having to go to the web page. It's especially useful to see the types of the callback functions.
> python: Include script examples in function docstring

- cmake/FindENCHANT.cmake
I have tested with enchant-2 and confirmed that the spell checker works well.
> cmake: add support of compiling with enchant-2 for the Spell checker plugin

- src/gui/gui-buffer.c
- src/plugins/irc/irc-tag.c
- src/plugins/relay/relay-config.c
fixed some typos in code comments
> fix: various code comments

- src/plugins/fifo/fifo.c
This allows you to use escape characters if you start the fifo command with \ instead of *, in the same way as the escape_commands option in the relay protocol. This allows you to send commands consisting of multiple lines by using \n if the buffer has input_multiline set.
> fifo: allow using escape characters

- src/core/wee-crypto.c
- tests/scripts/python/testapi.py
- tests/unit/core/test-core-infolist.cpp
These issues were spotted when running tests on s390x system.
> Fix few endianness issues

- src/core/wee-network.c
- src/plugins/relay/relay-server.c
inet_pton() can return values < 0.
> core, relay: make inet_pton() return value checks more strict

- doc/sr/weechat_dev.sr.adoc
- doc/sr/weechat_faq.sr.adoc
- doc/sr/weechat_plugin_api.sr.adoc
- doc/sr/weechat_user.sr.adoc
- po/sr.po
Here is the update of Serbian messages and documentation translation.
> Update of Serbian translation

- doc/sr/weechat_dev.sr.adoc
- doc/sr/weechat_plugin_api.sr.adoc
- doc/sr/weechat_user.sr.adoc
- po/sr.po
Here is an update of Serbian translation, messages and documentation.
> Update Serbian translation

- tests/scripts/python/testapigen.py
- tests/scripts/python/unparse.py
See https://github.com/python/cpython/pull/119563.
> tests: migrate away from removed ast features

- doc/sr/weechat_dev.sr.adoc
Here is an update of the Serbian documentation translation
> doc: update Serbian documentation
